# Business Development {#bd}

A major question folks have in stepping out of academia is how exactly they will get funding.
In general (non-academic) spaces, this is often referred to as [business development](#d_business_development), which more generally refers to the processes used to create a capital-based organization.



## Leveraging Existing Projects

As scientists, we develop personal and intimate knowledge of the research projects we work on.
In the context of establishing new lines of funding for your organization, it is important to acknoweledge when your specialization is to a point that it is not efficient (from a business perspective) for your former employer to hire and train up new staff.
When you are in such a position, you hold important power within the project, which can be useful in retaining your position within the project even if your employment position changes.
This specialized training-based power affords you negotiating leverage that, when used appropriately, supports continuation and possibly expansion of the project. However, this leverage can easily be misued and has the potential to result in your connection to the project being severed; after all, someone else *can* be trained up on it.

All that is to say leveraging existing projects can be a key contributor to establishing your freelance self, but must be done in an appropriate, collaborative fashion.

### From Employee to Subcontractor



## Listservs

## Cold Calls/Cold E-mails

## Meetings

### Local Conferences

### (Inter)National Conferences